version: 2

# Circle jobs
jobs:

  # Verify code and run tests
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm test

  # Publish the module to npm
  publish:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Authenticate with npm
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run:
          name: Publish to npm
          command: make npm-publish

# Circle workflows
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /v.*/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
